#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

# virtualenvwrapper doesn't work with "set -e
function check_worked {
    if ! $*
    then
        echo "NO"
    fi
}

cd test-projects

workon pubsubpull_1.7
cd django_1_7
echo Django 1.7
check_worked python manage.py test pubsubpull
cd ..


workon pubsubpull_1.9
cd django_1_9
echo Django 1.9
check_worked python manage.py test pubsubpull
cd ..