#!/usr/bin/env bash
cd `dirname $0`
source virtualenvwrapper.sh

#mkvirtualenv pubsubpull_1.4
#pip install -U -r common.pip -r django_1_4/setup.pip
#pip freeze
#deactivate

mkvirtualenv  pubsubpull_1.7
pip install -U -r common.pip -r django_1_7/setup.pip
pip freeze
deactivate

mkvirtualenv  pubsubpull_1.9
pip install -U -r common.pip -r django_1_9/setup.pip
pip freeze
deactivate

mkvirtualenv  pubsubpull_1.11
pip install -U -r common.pip -r django_1_11/setup.pip
pip freeze
deactivate
